const USERNAMR_PASSWORD_EMPTY = 'USERNAMR_PASSWORD_EMPTY'
const USERNAMR_ALREADY_EXITS = 'USERNAMR_ALREADY_EXITS'

const USERNAME_DOES_NOT_EXITS = 'USERNAME_DOES_NOT_EXITS'
const PASSWORD_NOT_INCRE = 'PASSWORD_NOT_INCRE'
const UNAUTHORIZAYION = 'UNAUTHORIZAYION'
const TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY'
const UNPERMISSION = 'UNPERMISSION'

module.exports = {
  USERNAMR_PASSWORD_EMPTY,
  USERNAMR_ALREADY_EXITS,
  USERNAME_DOES_NOT_EXITS,
  PASSWORD_NOT_INCRE,
  UNAUTHORIZAYION,
  TOKEN_IS_EMPTY,
  UNPERMISSION
}

